/**
 * 
 */
package net.zdsoft.eis.base.annotation.field;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

import net.zdsoft.eis.base.annotation.annotationtype.Scope;
import net.zdsoft.eis.base.constant.enumeration.SchoolType;

/**
 * 学校类型范围
 * @author zhangkc
 * @date 2015年4月23日 下午8:26:36
 */
@Target(java.lang.annotation.ElementType.FIELD)
@Retention(RetentionPolicy.RUNTIME)
@Scope
public @interface SchoolTypeScope {
	/**
	 * 学校类型范围，默认所有学校类型
	 * @return
	 * @author zhangkc
	 * @date 2015年4月24日 上午11:11:55
	 */
	SchoolType[] scope() default {
		SchoolType.PREEDU, SchoolType.PREEDU_MINORITY, SchoolType.PREEDU_ATTACHED, 	
		SchoolType.PRIMARY, SchoolType.PRIMARY_MINORITY, SchoolType.PRIMARY_MULTYLE_YEAR, SchoolType.PRIMARY_TEACHSCH, SchoolType.PRIMARY_ATTACHED, 	
		SchoolType.PRIMARY_ADULT_STAFF, SchoolType.PRIMARY_ADULT_FARMER, SchoolType.PRIMARY_ADULT_CLASS, SchoolType.PRIMARY_ADULT_ELIMINATE_ILLITERACY, 	
		SchoolType.JUNIOR, SchoolType.JUNIOR_NINEYEAR, SchoolType.JUNIOR_MINORITY, SchoolType.JUNIOR_MINORITY_NINEYEAR, SchoolType.JUNIOR_ATTACHED, 	
		SchoolType.JUNIOR_CAREER, SchoolType.JUNIOR_CAREER_MINORITY, SchoolType.JUNIOR_CAREER_MIDDLE_SCHOOL_ATTACHED, SchoolType.JUNIOR_CAREER_ATTACHED, 	
		SchoolType.JUNIOR_ADULT_STAFF, SchoolType.JUNIOR_ADULT_FARMER, 	
		SchoolType.SENIOR_FULL, SchoolType.SENIOR, SchoolType.SENIOR_FULL_MINORITY, SchoolType.SENIOR_MINORITY, SchoolType.SENIOR_TWELVEYEAR, SchoolType.SENIOR_ATTACHED, 	
		SchoolType.SENIOR_ADULT_STAFF, SchoolType.SENIOR_ADULT_FARMER, 	
		SchoolType.SECONDARY_VOCATIONAL, SchoolType.SECONDARY_VOCATIONAL_TECHNICAL, SchoolType.SECONDARY_VOCATIONAL_TEACHER_TRAINING, SchoolType.SECONDARY_VOCATIONAL_ADULT, SchoolType.SECONDARY_VOCATIONAL_CAREER, SchoolType.SECONDARY_VOCATIONAL_SKILLED_WORKER, SchoolType.SECONDARY_VOCATIONAL_ATTACHED, SchoolType.SECONDARY_VOCATIONAL_OTHER, 	
		SchoolType.REFORM_SCHOOL, 	
		SchoolType.HIGHER_EDUCATION_UNIVERSITY, SchoolType.HIGHER_EDUCATION_COLLEGE, SchoolType.HIGHER_EDUCATION_INDEPENDENT_INSTITUTE, SchoolType.HIGHER_EDUCATION_SPECIALIST, SchoolType.HIGHER_EDUCATION_VOCATIONAL, SchoolType.HIGHER_EDUCATION_OTHER, 	
		SchoolType.ADULT_HIGHER_EDUCATION_STAFF, SchoolType.ADULT_HIGHER_EDUCATION_FARMER, SchoolType.ADULT_HIGHER_EDUCATION_CADRE, SchoolType.ADULT_HIGHER_EDUCATION_EDUCATION_COLLEGE, SchoolType.ADULT_HIGHER_EDUCATION_CORRESPONDENCE, SchoolType.ADULT_HIGHER_EDUCATION_RADIO_TELEVISION, SchoolType.ADULT_HIGHER_EDUCATION_OTHER, 	
		SchoolType.SPECIAL_EDUCATION_BLIND, SchoolType.SPECIAL_EDUCATION_DEAF, SchoolType.SPECIAL_EDUCATION_MENTALLY_RETARDED, SchoolType.SPECIAL_EDUCATION_OTHER, SchoolType.SPECIAL_EDUCATION_PRIMARY_ATTACHED, SchoolType.SPECIAL_EDUCATION_JUNIOR_ATTACHED, 	
		SchoolType.POSTGRADUATE, 	
		SchoolType.OTHER_HIGHER_EDUCATION, 	
		SchoolType.MEDIUM_CAREER_EDUCATION_STAFF, SchoolType.MEDIUM_CAREER_EDUCATION_FARMER, SchoolType.MEDIUM_CAREER_EDUCATION_OTHER
	};
}
