package net.zdsoft.eis.sms.entity;

import java.util.HashSet;
import java.util.Set;

import net.zdsoft.eis.frame.entity.HibernateEntity;

/**
 * SmsBatch generated by MyEclipse - Hibernate Tools
 */

public class SmsBatch extends HibernateEntity {

	private static final long serialVersionUID = 1L;

	// Fields

	private String userId;
	private String taskId;
	private String depId;
	private String unitId;
	private String sendDate;
	private String content;
	private String smsType;
	private Integer sendHour;
	private Integer sendMinutes;
	private String feastDayname;
	private String dep;
	private String userName;
	private String status;
	private String statusdesc;
	
	
	
	

	/**
	 * 短信详细发送信息
	 */
	private Set<SmsSend> sendSet;
	/**
	 * 组装后的发送时间
	 */
	private String sendtime;


	public Set<SmsSend> getSendSet() {
		return sendSet;
	}

	public void setSendSet(Set<SmsSend> sendSet) {
		this.sendSet = sendSet;
	}
	
	public void addSmsDetailEntity(SmsSend smsSend) {
		if (this.sendSet == null) {
			this.sendSet = new HashSet<SmsSend>();
		}

		smsSend.setParent(this);
		this.sendSet.add(smsSend);
	}
	
	public String getSendtime() {
		String _year = this.getSendDate().substring(0, 4);
		String _month = this.getSendDate().substring(4, 6);
		String _day = this.getSendDate().substring(6, 8);
		String _hour = this.getSendHour().toString();

		if (_hour.length() == 1) {
			_hour = "0" + _hour;
		}

		String _minute = this.getSendMinutes().toString();

		if (_minute.length() == 1) {
			_minute = "0" + _minute;
		}

		this.setSendtime(_year + "-" + _month + "-" + _day + " " + _hour + ":"
				+ _minute);

		return sendtime;
	}

	public void setSendtime(String sendtime) {
		this.sendtime = sendtime;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getTaskId() {
		return taskId;
	}

	public void setTaskId(String taskId) {
		this.taskId = taskId;
	}

	public String getDepId() {
		return depId;
	}

	public void setDepId(String depId) {
		this.depId = depId;
	}

	public String getUnitId() {
		return unitId;
	}

	public void setUnitId(String unitId) {
		this.unitId = unitId;
	}

	public String getSendDate() {
		return sendDate;
	}

	public void setSendDate(String sendDate) {
		this.sendDate = sendDate;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getSmsType() {
		return smsType;
	}

	public void setSmsType(String smsType) {
		this.smsType = smsType;
	}

	public Integer getSendHour() {
		return sendHour;
	}

	public void setSendHour(Integer sendHour) {
		this.sendHour = sendHour;
	}

	public Integer getSendMinutes() {
		return sendMinutes;
	}

	public void setSendMinutes(Integer sendMinutes) {
		this.sendMinutes = sendMinutes;
	}

	public String getFeastDayname() {
		return feastDayname;
	}

	public void setFeastDayname(String feastDayname) {
		this.feastDayname = feastDayname;
	}

	public String getDep() {
		return dep;
	}

	public void setDep(String dep) {
		this.dep = dep;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getStatusdesc() {
		return statusdesc;
	}

	public void setStatusdesc(String statusdesc) {
		this.statusdesc = statusdesc;
	}





}