package net.zdsoft.eis.base.common.entity;

import java.util.Date;

import net.zdsoft.eis.frame.client.BaseEntity;


/**
 * BasicDateinfo generated by MyEclipse - Hibernate Tools
 */

public class DateInfo  extends BaseEntity{

    private static final long serialVersionUID = 365701413490011553L;
    private String schid;
     private Date date;
     private String acadyear;
     private String semester;
     private Integer week;
     private String weekday;
     private String isfeast;
     private String feastname;
     private int month;
    // Constructors
     
    /** default constructor */
    public DateInfo() {
    }
    
	public int getMonth() {
		return month;
	}

	public void setMonth(int month) {
		this.month = month;
	}

	public String getSchid() {
        return this.schid;
    }
    
    public void setSchid(String schid) {
        this.schid = schid;
    }

    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    public String getAcadyear() {
        return this.acadyear;
    }
    
    public void setAcadyear(String acadyear) {
        this.acadyear = acadyear;
    }

    public String getSemester() {
        return this.semester;
    }
    
    public void setSemester(String semester) {
        this.semester = semester;
    }

    public Integer getWeek() {
        return this.week;
    }
    
    public void setWeek(Integer week) {
        this.week = week;
    }

    public String getWeekday() {
        return this.weekday;
    }
    
    public void setWeekday(String weekday) {
        this.weekday = weekday;
    }

    public String getIsfeast() {
        return this.isfeast;
    }
    
    public void setIsfeast(String isfeast) {
        this.isfeast = isfeast;
    }

    public String getFeastname() {
        return this.feastname;
    }
    
    public void setFeastname(String feastname) {
        this.feastname = feastname;
    }

}