package net.zdsoft.eis.base.common.entity;

import java.util.Set;

import net.zdsoft.eis.frame.client.BaseEntity;

/**
 * Cnet2SysRole generated by MyEclipse - Hibernate Tools
 */

public class Role extends BaseEntity {

    // Fields

    /**
     * Comment for <code>serialVersionUID</code>
     */
    private static final long serialVersionUID = 8159822019310571151L;
    private String identifier;
    private String unitid;
    private String name;
    private String modid;
    private String operid;
    private String dynamicdataset;
    private boolean isactive;
    private String description;
    private String subsystem;
    private Integer refid;
    private Integer roletype;

    // =================辅助字段=================
    //界面维护使用
    private String isactiveString;
    private String roletypeString;
    private Set<Long> selectedModSet;
    private Set<Long> selectedOperSet;    
   
    private Integer unitClass;
    private boolean inUse;
    private boolean checked;

    //权限使用
    private Set<Module> modSet;
    private Set<String> operSet;
    private Set<Integer> subSystemSet;
    private Set<String> extraSubSystemSet;
	// ************************************
	// 角色标识定义
	// ************************************
	public static final String ROLE_IDENTIFIER_DEFAULT = "default"; // 默认角色标识
	// ************************************
	// 角色类型定义
	// ************************************
	public static final int ROLE_TYPE_OPER = 0; // 业务角色
	public static final int ROLE_TYPE_SUBADMIN = 1; // 子系统管理员角色
	public static final int ROLE_TYPE_UNITADMIN = 2; // 单位管理员角色
	public static final int ROLE_TYPE_COMMON = 3; // 普通角色
    
    // Constructors

    /** default constructor */
    public Role() {
    }

    public String getIdentifier() {
        return this.identifier;
    }

    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    public String getUnitid() {
        return this.unitid;
    }

    public void setUnitid(String unitid) {
        this.unitid = unitid;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getModid() {
        return this.modid;
    }

    public void setModid(String modid) {
        this.modid = modid;
    }

    public String getOperid() {
        return this.operid;
    }

    public void setOperid(String operid) {
        this.operid = operid;
    }

    public String getDynamicdataset() {
        return this.dynamicdataset;
    }

    public void setDynamicdataset(String dynamicdataset) {
        this.dynamicdataset = dynamicdataset;
    }

    public boolean getIsactive() {
        return this.isactive;
    }

    public void setIsactive(boolean isactive) {
        this.isactive = isactive;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getSubsystem() {
        return this.subsystem;
    }

    public void setSubsystem(String subsystem) {
        this.subsystem = subsystem;
    }

    public Integer getRefid() {
        return this.refid;
    }

    public void setRefid(Integer refid) {
        this.refid = refid;
    }

    public Integer getRoletype() {
        return this.roletype;
    }

    public void setRoletype(Integer roletype) {
        this.roletype = roletype;
    }

    public String getIsactiveString() {
        return isactiveString;
    }

    public void setIsactiveString(String isactiveString) {
        this.isactiveString = isactiveString;
    }

    public String getRoletypeString() {
        return roletypeString;
    }

    public void setRoletypeString(String roletypeString) {
        this.roletypeString = roletypeString;
    }

    public Set<Long> getSelectedModSet() {
        return selectedModSet;
    }

    public void setSelectedModSet(Set<Long> selectedModSet) {
        this.selectedModSet = selectedModSet;
    }

    public Set<Long> getSelectedOperSet() {
        return selectedOperSet;
    }

    public void setSelectedOperSet(Set<Long> selectedOperSet) {
        this.selectedOperSet = selectedOperSet;
    }

    public Set<Module> getModSet() {
        return modSet;
    }

    public void setModSet(Set<Module> modSet) {
        this.modSet = modSet;
    }

    public Set<String> getOperSet() {
        return operSet;
    }

    public void setOperSet(Set<String> operSet) {
        this.operSet = operSet;
    }

    public Set<Integer> getSubSystemSet() {
        return subSystemSet;
    }

    public void setSubSystemSet(Set<Integer> subSystemSet) {
        this.subSystemSet = subSystemSet;
    }

    public Set<String> getExtraSubSystemSet() {
        return extraSubSystemSet;
    }

    public void setExtraSubSystemSet(Set<String> extraSubSystemSet) {
        this.extraSubSystemSet = extraSubSystemSet;
    }

    public Integer getUnitClass() {
        return unitClass;
    }

    public void setUnitClass(Integer unitClass) {
        this.unitClass = unitClass;
    }

    public boolean isInUse() {
        return inUse;
    }

    public void setInUse(boolean inUse) {
        this.inUse = inUse;
    }

    public boolean isChecked() {
        return checked;
    }

    public void setChecked(boolean checked) {
        this.checked = checked;
    }

}
