package net.zdsoft.eis.base.common.entity;

import net.zdsoft.eis.base.constant.BaseConstant;
import net.zdsoft.keelcnet.entity.EntityObject;

/**
 * CnetModel generated by MyEclipse - Hibernate Tools
 */

public class SubSystem extends EntityObject {
	/**
	 * Comment for <code>serialVersionUID</code>
	 */
	private static final long serialVersionUID = 1276870093630212518L;

	private String name;
	private String code;
	private Integer markbit;
	private String rolegroup;
	private String indexUrl;
	private Integer mark;
	private String image;
	private String isControlByPerm;
	private String build;
	private String curVersion;
	private Integer orderid;
	private Integer type;
	private Integer serverId;
	private Integer serverType;
	private String introductionPage;
	private String tabShortPage;
	private String description;
	private Integer canDistributed;
	private Integer initUnitOpen; // 单位开通时是否初始化的系统, 1 表示必须要开通，0 表示不开通， 2 表示不显示
	private Integer multiScreen;//该子系统下的模块是否多屏
	private Integer parentId;//父节点
	private String source;//来源
	private String sortType;//分类类型
	// ===============辅助字段==============
	private String appRegistryId;
	
	/**
	 * 服务类型 对应serverType
	 */
	public static final int SERVER_TYPE_GROUP_FREE = 1; // 集团订购免费使用
	public static final int SERVER_TYPE_GROUP_PERSONAL_OPEN = 2; // 集团订购个人开通
	public static final int SERVER_TYPE_PERSONAL_OPEN = 3; // 个人订购
	public static final int SERVER_TYPE_FREE = 4; // 免费
	public static final String SUBSYSTEM_NAME_ARCHIVE = "archive";// 公文子系统产品标识

	/**
	 * 来源 对应Source
	 */
	public static final String SOURCE_LOCAL = "1"; // 本地
	public static final String SOURCE_THIRD_PART_NORMAL = "2"; // 第三方
	public static final String SOURCE_THIRD_PART_SPECIAL = "3"; // 第三方特殊
	
   /**
     * 子系统标识：学生平台
     */
    public static final int SUBSYSTEM_STUPLATFORM = -1;

    /**
     * 子系统标识：管理平台
     */
    public static final int SUBSYSTEM_BACKGROUND = -2;
    
	/**
	 * 子系统标识：公文为1
	 */
	public static final int SUBSYSTEM_ARCHIVE = 1;

	/**
	 * 子系统标识：办公为2
	 */
	public static final int SUBSYSTEM_OFFICE = 2;

	/**
	 * 学籍
	 */
	public static final int SUBSYSTEM_STUSYS = 10;

	/**
	 * 人事
	 */
	public static final int SUBSYSTEM_PERSONNEL = 11;
	
	/**
	 * 培训
	 */
	public static final int SUBSYSTEM_CULTIVATE = 21;

	/**
	 * 德育
	 */
	public static final int SUBSYSTEM_STUWORK = 38;
	
	/**
	 * 实习
	 */
	public static final int SUBSYSTEM_PRACTICE = 44;
	
	/**
	 * 教务管理系统PB
	 */
	public static final int SUBSYSTEM_TCHSYS = 50;
	
	/**
	 * 教材guanl
	 */
	public static final int SUBSYSTEM_TEXTBOOK = 50;

	/**
	 * 人事科研管理系统
	 */
	public static final int SUBSYSTEM_EMPSYS = 51;

	/**
	 * 德育管理系统
	 */
	public static final int SUBSYSTEM_ZHSTUWORK = 53;

	/**
	 * 教职工考核
	 */
	public static final int SUBSYSTEM_EVALUATE = 54;

	/**
	 * 数据挖掘
	 */
	public static final int SUBSYSTEM_STATREPORT = 55;

	/**
	 * 电子文档系统
	 */
	public static final int SUBSYSTEM_EFILE = 77;

	/**
	 * 校产
	 */
	public static final int SUBSYSTEM_SCHRES = 66;

	/**
	 * 综合素质
	 */
	public static final int SUBSYSTEM_DIATHESIS = 67;

	/**
	 * 个人中心的成绩查询
	 */
	public static final int SUBSYSTEM_ACHIEVEMENT_QUERY = 98;

	/**
	 * 系统管理
	 */
	public static final int SUBSYSTEM_SYSTEM = 99;

	/**
	 * 教育事业统计
	 */
	public static final int SUBSYSTEM_DATACENTER = 96;
	
	public static final String SUBSYSTEM_ACHIEVEMENT_QUERY_CODE = "personalCenter"; // 个人中心的成绩查询

	/**
	 * 应用系统类型 本地自带子应用系统
	 */
	public static final String APP_SYSTEM_TYPE_LOCAL = "1";
	/**
	 * 应用系统类型 注册的子应用系统
	 */
	public static final String APP_SYSTEM_TYPE_REGISTRY = "2";
	/**
	 * 应用系统类型 运营平台注册的子系统
	 */
	public static final String APP_SYSTEM_TYPE_CENTER = "3";
	/**
	 * 应用系统类型 内嵌到系统中的子系统，其他的和1一样，只是打开方式不同，就像个人中心的成绩查询
	 */
	public static final String APP_SYSTEM_TYPE_INNER_PERSONAL = "4";
	/**
	 * 应用系统类型 隐藏的系统，如短信服务系统
	 */
	public static final String APP_SYSTEM_TYPE_HIDDEN = "5";
	/**
	 * 家校互联名称 pasport中，家校互联id
	 */
	public static final int ETOH_SUBSYSTEM_ID = 6;

	/**
	 * 根据子系统id取web title的值(从原来的WebConfig迁移过来)
	 * @author "yangk" 
	 * @date Apr 9, 2010 2:59:35 PM
	 *
	 * @param appId
	 * @return
	 */
	public static final String getTitle(int appId) {
		String title;
		switch (appId) {
		case SUBSYSTEM_STUPLATFORM:
            title = "学生管理平台";
            break;            
		case SUBSYSTEM_BACKGROUND:
            title = "后台管理";
            break;
		case SUBSYSTEM_ARCHIVE:
			title = "公文流转系统";
			break;
		case SUBSYSTEM_OFFICE:
			title = "办公信息系统";
			break;
		case SUBSYSTEM_STUSYS:
			title = "学籍管理系统";
			break;
		case SUBSYSTEM_EMPSYS:
			title = "人事科研管理系统";
			break;
		case SUBSYSTEM_TCHSYS:
			title = "教务管理系统";
			break;
		case SUBSYSTEM_ZHSTUWORK:
			title = "德育管理系统";
			break;
		case SUBSYSTEM_EVALUATE:
			title = "教职工考核系统";
			break;
		case SUBSYSTEM_STATREPORT:
			title = "数据挖掘系统";
			break;
		case SUBSYSTEM_SYSTEM:
			title = "系统平台管理";
			break;
		default:
			title = "管理平台";
		}
		return title;
	}
    
	/**
	 * 帮助地址
	 * @param appId
	 * @return
	 */
	public String getHelpPath(int platform) {
        String path;
        switch (platform) {
        case BaseConstant.PLATFORM_STUPLATFORM:
            path = "/stuplatform/help/";
            break;
        case BaseConstant.PLATFORM_BACKGROUND:
            path = "/background/help/";
            break;
        default:
            path = "/help/" + code + "/";
            break;
        }
        return path;
    }
	
	public String getBuild() {
		return build;
	}

	public void setBuild(String build) {
		this.build = build;
	}

	public Integer getCanDistributed() {
		return canDistributed;
	}

	public void setCanDistributed(Integer canDistributed) {
		this.canDistributed = canDistributed;
	}

	public String getCurVersion() {
		return curVersion;
	}

	public void setCurVersion(String curVersion) {
		this.curVersion = curVersion;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String identity) {
		this.code = identity;
	}

	public Integer getMarkbit() {
		return markbit;
	}

	public void setMarkbit(Integer markbit) {
		this.markbit = markbit;
	}

	public String getRolegroup() {
		return rolegroup;
	}

	public void setRolegroup(String rolegroup) {
		this.rolegroup = rolegroup;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getIndexUrl() {
		return indexUrl;
	}

	public void setIndexUrl(String indexUrl) {
		this.indexUrl = indexUrl;
	}

	public Integer getMark() {
		return mark;
	}

	public void setMark(Integer mark) {
		this.mark = mark;
	}

	public String getImage() {
		return image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public String getIsControlByPerm() {
		return isControlByPerm;
	}

	public void setIsControlByPerm(String isControlByPerm) {
		this.isControlByPerm = isControlByPerm;
	}

	public Integer getOrderid() {
		return orderid;
	}

	public void setOrderid(Integer orderid) {
		this.orderid = orderid;
	}

	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Integer getServerId() {
		return serverId;
	}

	public void setServerId(Integer serverId) {
		this.serverId = serverId;
	}

	public Integer getServerType() {
		return serverType;
	}

	public void setServerType(Integer serverType) {
		this.serverType = serverType;
	}

	public String getIntroductionPage() {
		return introductionPage;
	}

	public void setIntroductionPage(String introductionPage) {
		this.introductionPage = introductionPage;
	}

	public String getTabShortPage() {
		return tabShortPage;
	}

	public void setTabShortPage(String tabShortPage) {
		this.tabShortPage = tabShortPage;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getInitUnitOpen() {
		return initUnitOpen;
	}

	public void setInitUnitOpen(Integer initUnitOpen) {
		this.initUnitOpen = initUnitOpen;
	}

	public String getAppRegistryId() {
		return appRegistryId;
	}

	public void setAppRegistryId(String appRegistryId) {
		this.appRegistryId = appRegistryId;
	}

	public Integer getMultiScreen() {
		return multiScreen;
	}

	public void setMultiScreen(Integer multiScreen) {
		this.multiScreen = multiScreen;
	}

	public Integer getParentId() {
		return parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public String getSource() {
		return source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public String getSortType() {
		return sortType;
	}

	public void setSortType(String sortType) {
		this.sortType = sortType;
	}
}
