package net.zdsoft.eis.base.common.entity;

import net.zdsoft.eis.frame.client.BaseEntity;

/**
 * SuWare generated by MyEclipse Persistence Tools
 */

public class Ware extends BaseEntity {

    private static final long serialVersionUID = 1634468587166930255L;

    /**
     * 状态：正常
     */
    public static final int STATE_NORMAL = 1;
    
    /**
     * 定购规则：无须订购，个人需授权
     */
    public static final int ORDER_RULE_AUTHORIZE = 7;

    /**
     * 角色类型：学生
     */
    public static final int ROLE_TYPE_STUDENT = 1;
    /**
     * 角色类型：教师
     */
    public static final int ROLE_TYPE_TEACHER = 2;
    /**
     * 角色类型：家长
     */
    public static final int ROLE_TYPE_FAMILY = 3;
    
    /**
     * 角色类型：教育局职工
     */
    public static final int ROLE_TYPE_EMPLOYEE = 4;
    
    /**
     * 角色类型：管理员
     */
    public static final int ROLE_TYPE_ADMIN = 5;
    
    private String code;
    private String name;
    private int wareFee;
    private int state;
    private long serverId;
    private long serverTypeId;
    private int subscriberType;
    private int nums;
    private int orderType;
    private String unitClass;
    private String role;
    private int experienceMonth;
    private int isFee;
    private int teacherRule;
    private int studentRule;
    private int familyRule;
    private int adminRule;
    private String serverCode;

    // Constructors

    /** default constructor */
    public Ware() {
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getWareFee() {
        return wareFee;
    }

    public void setWareFee(int wareFee) {
        this.wareFee = wareFee;
    }

    public int getState() {
        return state;
    }

    public void setState(int state) {
        this.state = state;
    }

    public long getServerId() {
        return serverId;
    }

    public void setServerId(long serverId) {
        this.serverId = serverId;
    }

    public long getServerTypeId() {
        return serverTypeId;
    }

    public void setServerTypeId(long serverTypeId) {
        this.serverTypeId = serverTypeId;
    }

    public int getSubscriberType() {
        return subscriberType;
    }

    public void setSubscriberType(int subscriberType) {
        this.subscriberType = subscriberType;
    }

    public int getNums() {
        return nums;
    }

    public void setNums(int nums) {
        this.nums = nums;
    }

    public int getOrderType() {
        return orderType;
    }

    public void setOrderType(int orderType) {
        this.orderType = orderType;
    }

    public String getUnitClass() {
        return unitClass;
    }

    public void setUnitClass(String unitClass) {
        this.unitClass = unitClass;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public int getExperienceMonth() {
        return experienceMonth;
    }

    public void setExperienceMonth(int experienceMonth) {
        this.experienceMonth = experienceMonth;
    }

    public int getIsFee() {
        return isFee;
    }

    public void setIsFee(int isFee) {
        this.isFee = isFee;
    }

    public int getTeacherRule() {
        return teacherRule;
    }

    public void setTeacherRule(int teacherRule) {
        this.teacherRule = teacherRule;
    }

    public int getStudentRule() {
        return studentRule;
    }

    public void setStudentRule(int studentRule) {
        this.studentRule = studentRule;
    }

    public int getFamilyRule() {
        return familyRule;
    }

    public void setFamilyRule(int familyRule) {
        this.familyRule = familyRule;
    }

    public int getAdminRule() {
        return adminRule;
    }

    public void setAdminRule(int adminRule) {
        this.adminRule = adminRule;
    }

    public String getServerCode() {
        return serverCode;
    }

    public void setServerCode(String serverCode) {
        this.serverCode = serverCode;
    }

}
