package net.zdsoft.eis.base.data.entity;

import net.zdsoft.eis.frame.client.BaseEntity;

/**
 * AbstractCnet2SysUser generated by MyEclipse - Hibernate Tools
 */

public class Duty extends BaseEntity {
    /**
     * 
     */
    private static final long serialVersionUID = -4908222817567884575L;
    private String unitId;
    private String thisId;
    private String content;
    private int type;
    private long updatestamp;
    private String isDeleted;

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getIsDeleted() {
        return isDeleted;
    }

    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }

    public String getThisId() {
        return thisId;
    }

    public void setThisId(String thisId) {
        this.thisId = thisId;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public String getUnitId() {
        return unitId;
    }

    public void setUnitId(String unitId) {
        this.unitId = unitId;
    }

    public long getUpdatestamp() {
        return updatestamp;
    }

    public void setUpdatestamp(long updatestamp) {
        this.updatestamp = updatestamp;
    }
}