package net.zdsoft.office.teacherLeave.service;import java.util.*;import net.zdsoft.office.teacherLeave.entity.OfficeTeacherLeave;import net.zdsoft.eis.component.flowManage.entity.Flow;import net.zdsoft.jbpm.core.entity.TaskHandlerSave;import net.zdsoft.keel.util.Pagination;import net.zdsoft.keelcnet.action.UploadFile;/** * office_teacher_leave  * @author  *  */public interface OfficeTeacherLeaveService {	/**	 * 新增office_teacher_leave	 * @param officeTeacherLeave	 * @return	 */	public OfficeTeacherLeave save(OfficeTeacherLeave officeTeacherLeave);		/**	 * 根据ids数组删除office_teacher_leave数据	 * @param ids	 * @return	 */	public Integer delete(String[] ids);		/**	 * 更新office_teacher_leave	 * @param officeTeacherLeave	 * @return	 */	public Integer update(OfficeTeacherLeave officeTeacherLeave);		/**	 * 根据id获取office_teacher_leave	 * @param id	 * @return	 */	public OfficeTeacherLeave getOfficeTeacherLeaveById(String id);		public String  getTextComment(String unitId,String userId);		public OfficeTeacherLeave getOfficeTeacherByOfficeLog(OfficeTeacherLeave officeTeacherLeave,String unitId,String userId);	/**	 * 根据ids数组查询office_teacher_leavemap	 * @param ids	 * @return	 */	public Map<String, OfficeTeacherLeave> getOfficeTeacherLeaveMapByIds(String[] ids);		/**	 * 获取office_teacher_leave列表	 * @return	 */	public List<OfficeTeacherLeave> getOfficeTeacherLeaveList();		/**	 * 分页获取office_teacher_leave列表	 * @param page	 * @return	 */	public List<OfficeTeacherLeave> getOfficeTeacherLeavePage(Pagination page);	

	/**
	 * 根据UnitId获取office_teacher_leave列表
	 * @param unitId
	 * @return
	 */
	public List<OfficeTeacherLeave> getOfficeTeacherLeaveByUnitIdList(String unitId);		/**	 * 根据unitId获取office_teacher_leave列表	 * @param unitId	 * @return	 */	public List<OfficeTeacherLeave> getOfficeTeacherLeaveByUnitIdList(String[] unitId);

	/**
	 * 根据UnitId分页获取office_teacher_leave
	 * @param unitId
	 * @param page
	 * @return
	 */
	public List<OfficeTeacherLeave> getOfficeTeacherLeaveByUnitIdPage(String unitId, Pagination page);		/**	 * 获得你申请的请假信息	 * @param userId	 * @param unitId	 * @param applyStatus 	 * @param page	 * @return	 */	public List<OfficeTeacherLeave> getApplyList(String userId, String unitId,			int applyStatus, Pagination page);	/**	 * 请假查询	 * @param unitId	 * @param applyUserIds	 * @param startTime	 * @param endTime	 * @param page TODO	 * @return	 */	public List<OfficeTeacherLeave> getQueryList(String unitId,			String[] applyUserIds, Date startTime, Date endTime, Pagination page,boolean isSum);	public void update(OfficeTeacherLeave officeTeacherLeave, List<UploadFile> uploadFileList,boolean isMobile, String[] removeAttachment);	public OfficeTeacherLeave add(OfficeTeacherLeave officeTeacherLeave, List<UploadFile> uploadFileList,boolean isMobile);	public void startFlow(OfficeTeacherLeave officeTeacherLeave, String userId, List<UploadFile> uploadFileList,boolean isMobile, String[] removeAttachment);	/**	 * 未审核	 * @param userId	 * @param page	 * @return	 */	public List<OfficeTeacherLeave> toDoAudit(String userId, Pagination page);	/**	 * 我已审核	 * @param userId	 * @param page	 * @return	 */	public List<OfficeTeacherLeave> haveDoneAudit(String userId,String unitId, Pagination page);	/**	 * 已审核	 * @param userId	 * @param page	 * @return	 */	public List<OfficeTeacherLeave> HaveDoAudit(String userId,boolean invalid, Pagination page);	/**	 * 审核通过	 * @param pass	 * @param taskHandlerSave	 * @param id	 * @param currentStepId	 */	public void passFlow(boolean pass, TaskHandlerSave taskHandlerSave,			String id, String currentStepId);		/**	 * 获取统计信息	 * @return	 */	//public Map<String, String> getSumMap(String unitId, Date startTime, Date endTime, String deptId);	public Map<String, String> getSumMap(List<OfficeTeacherLeave> list,Date startTime, Date endTime);		/**	 * 相应时间段内的有请假信息的用户	 * @param unitId	 * @param startTime	 * @param endTime	 * @param deptId	 * @return	 */	public String[] getApplyUserIds(String unitId, Date startTime, Date endTime, String deptId);	/**	 * 撤销已提交的申请	 * @param id	 * 2016年9月11日	 */	public void deleteRevoke(String id);	/**	 * 作废申请通过的申请	 * @param id	 * 2016年9月11日	 */	public void deleteInvalid(String id,String userId);		/**	 * 保存修改的流程并启动流程	 * @param leaveId	 * @param userId	 * @param flowId	 * @param jsonResult	 */	public void changeFlow(String leaveId, String userId, String flowId, String jsonResult);		/**	 * 根据条件筛选流程	 * @param flowList	 * @param unitId	 * @param userId	 * @return	 */	public List<Flow> filterFlow(List<Flow> flowList, String unitId, String userId);		public List<OfficeTeacherLeave> getOfficeTeacherLeavesByUnitIdAndUserId(String unitId,String userId,Date date);}